services:
    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WATCHTOWER_CLEANUP: 'true' # 更新成功后删除旧镜像
            WATCHTOWER_SCHEDULE: '0 4 * * *' # 每天凌晨 4 点检查一次
            WATCHTOWER_LABEL_ENABLE: 'true' # 仅监控带 watchtower.enable=true 标签的容器
            WATCHTOWER_DEBUG: 'false'
